import { VerificationResult } from './types';

export const mockVerificationPass: VerificationResult = {
  runId: 'VR-20260114-001',
  timestamp: '2026-01-14T10:30:00Z',
  product: {
    asin: 'B01MSSDEPK',
    name: 'The Ordinary Hyaluronic Acid 2% + B5',
  },
  status: 'COMPLETE',
  modules: [
    {
      id: 'M1',
      name: 'Product Context',
      status: 'PASS',
      checksTotal: 7,
      checksPassed: 7,
      checksFailed: 0,
      checks: [
        { id: 'M1-01', name: 'Product type present', status: 'PASS', detail: 'Serum' },
        { id: 'M1-02', name: 'Category path valid', status: 'PASS', detail: 'Beauty > Skincare > Face > Serums' },
        { id: 'M1-03', name: 'Minimum attributes', status: 'PASS', detail: '7 attributes (need ≥3)' },
        { id: 'M1-04', name: 'Initial keywords exist', status: 'PASS', detail: '12 keywords (need ≥3)' },
        { id: 'M1-05', name: 'Truth set complete', status: 'PASS', detail: 'All fields populated' },
        { id: 'M1-06', name: 'No banned terms', status: 'PASS', detail: '0 matches' },
        { id: 'M1-07', name: 'Source traceability', status: 'PASS', detail: '100% traceable' },
      ],
    },
    {
      id: 'M2',
      name: 'Competitor Discovery',
      status: 'PASS',
      checksTotal: 8,
      checksPassed: 8,
      checksFailed: 0,
      checks: [
        { id: 'M2-01', name: 'Search terms count', status: 'PASS', detail: '5 terms' },
        { id: 'M2-02', name: 'Raw list size', status: 'PASS', detail: '47 items' },
        { id: 'M2-03', name: 'No duplicates', status: 'PASS', detail: 'All unique' },
        { id: 'M2-04', name: 'Trimmed list size', status: 'PASS', detail: '20 items' },
        { id: 'M2-05', name: 'All have scores', status: 'PASS', detail: 'Range: 45-92' },
        { id: 'M2-06', name: 'Final list size', status: 'PASS', detail: '8 items' },
        { id: 'M2-07', name: 'Final from trimmed', status: 'PASS', detail: 'All valid' },
        { id: 'M2-08', name: 'ASINs valid format', status: 'PASS', detail: 'All match pattern' },
      ],
    },
    {
      id: 'M2.1',
      name: 'Customer Intent',
      status: 'PASS',
      checksTotal: 7,
      checksPassed: 7,
      checksFailed: 0,
      checks: [
        { id: 'M2.1-01', name: 'Themes count', status: 'PASS', detail: '7 themes' },
        { id: 'M2.1-02', name: 'Unique theme IDs', status: 'PASS', detail: 'All unique' },
        { id: 'M2.1-03', name: 'Theme names valid', status: 'PASS', detail: 'All from vocabulary' },
        { id: 'M2.1-04', name: 'Scores in range', status: 'PASS', detail: 'All 0-100' },
        { id: 'M2.1-05', name: 'Sample quotes exist', status: 'PASS', detail: '3-10 per theme' },
        { id: 'M2.1-06', name: 'Quotes traceable', status: 'PASS', detail: '42/42 verified' },
        { id: 'M2.1-07', name: 'No forbidden topics', status: 'PASS', detail: 'None found' },
      ],
    },
    {
      id: 'M2.3',
      name: 'USP Evaluation',
      status: 'PASS',
      checksTotal: 7,
      checksPassed: 7,
      checksFailed: 0,
      checks: [
        { id: 'M2.3-01', name: 'Minimum USPs', status: 'PASS', detail: '5 approved' },
        { id: 'M2.3-02', name: 'All have tags', status: 'PASS', detail: '5/5 tagged' },
        { id: 'M2.3-03', name: 'Proof points valid', status: 'PASS', detail: 'All verified' },
        { id: 'M2.3-04', name: 'Scores correct', status: 'PASS', detail: 'All within ±2' },
        { id: 'M2.3-05', name: 'No banned terms', status: 'PASS', detail: '0 matches' },
        { id: 'M2.3-06', name: 'Priority assigned', status: 'PASS', detail: '5/5 assigned' },
        { id: 'M2.3-07', name: 'Primary USPs exist', status: 'PASS', detail: '3 Primary' },
      ],
    },
    {
      id: 'M3',
      name: 'Keyword Intelligence',
      status: 'PASS',
      checksTotal: 8,
      checksPassed: 8,
      checksFailed: 0,
      checks: [
        { id: 'M3-01', name: 'Primary keywords', status: 'PASS', detail: '12 Primary' },
        { id: 'M3-02', name: 'All keywords scored', status: 'PASS', detail: '103 scored' },
        { id: 'M3-03', name: 'Score formula correct', status: 'PASS', detail: 'All verified' },
        { id: 'M3-04', name: 'All tiered', status: 'PASS', detail: 'No overlap' },
        { id: 'M3-05', name: 'No duplicates', status: 'PASS', detail: 'All unique' },
        { id: 'M3-06', name: 'USP bundles complete', status: 'PASS', detail: '5/5 bundles' },
        { id: 'M3-07', name: 'No risk-high in bundles', status: 'PASS', detail: 'None found' },
        { id: 'M3-08', name: 'Coverage adequate', status: 'PASS', detail: 'All ≥3' },
      ],
    },
    {
      id: 'M4',
      name: 'Listing Creation',
      status: 'PASS',
      checksTotal: 10,
      checksPassed: 10,
      checksFailed: 0,
      checks: [
        { id: 'M4-01', name: 'Title length', status: 'PASS', detail: '156 chars (max 200)' },
        { id: 'M4-02', name: 'Bullet count', status: 'PASS', detail: '5 bullets' },
        { id: 'M4-03', name: 'Bullet lengths', status: 'PASS', detail: 'All ≤500' },
        { id: 'M4-04', name: 'Description length', status: 'PASS', detail: '1847 chars (max 2000)' },
        { id: 'M4-05', name: 'Backend size', status: 'PASS', detail: '238 bytes (max 249)' },
        { id: 'M4-06', name: 'No banned terms', status: 'PASS', detail: '0 matches' },
        { id: 'M4-07', name: 'Keyword coverage', status: 'PASS', detail: '92%' },
        { id: 'M4-08', name: 'USP coverage', status: 'PASS', detail: '5/5 mentioned' },
        { id: 'M4-09', name: 'No ALL CAPS', status: 'PASS', detail: 'None found' },
        { id: 'M4-10', name: 'Quality score', status: 'PASS', detail: '94/100' },
      ],
    },
  ],
  summary: {
    totalChecks: 47,
    passed: 47,
    failed: 0,
    review: 0,
    blocked: 0,
  },
};

export const mockVerificationFail: VerificationResult = {
  runId: 'VR-20260114-002',
  timestamp: '2026-01-14T11:00:00Z',
  product: {
    asin: 'B09XYZ1234',
    name: 'New Face Cream Product',
  },
  status: 'BLOCKED',
  modules: [
    {
      id: 'M1',
      name: 'Product Context',
      status: 'PASS',
      checksTotal: 7,
      checksPassed: 7,
      checksFailed: 0,
      checks: [
        { id: 'M1-01', name: 'Product type present', status: 'PASS', detail: 'Face Cream' },
        { id: 'M1-02', name: 'Category path valid', status: 'PASS', detail: 'Beauty > Skincare > Face' },
        { id: 'M1-03', name: 'Minimum attributes', status: 'PASS', detail: '5 attributes' },
        { id: 'M1-04', name: 'Initial keywords exist', status: 'PASS', detail: '8 keywords' },
        { id: 'M1-05', name: 'Truth set complete', status: 'PASS', detail: 'All fields populated' },
        { id: 'M1-06', name: 'No banned terms', status: 'PASS', detail: '0 matches' },
        { id: 'M1-07', name: 'Source traceability', status: 'PASS', detail: '100% traceable' },
      ],
    },
    {
      id: 'M2',
      name: 'Competitor Discovery',
      status: 'PASS',
      checksTotal: 8,
      checksPassed: 8,
      checksFailed: 0,
      checks: [
        { id: 'M2-01', name: 'Search terms count', status: 'PASS', detail: '5 terms' },
        { id: 'M2-02', name: 'Raw list size', status: 'PASS', detail: '45 items' },
        { id: 'M2-03', name: 'No duplicates', status: 'PASS', detail: 'All unique' },
        { id: 'M2-04', name: 'Trimmed list size', status: 'PASS', detail: '20 items' },
        { id: 'M2-05', name: 'All have scores', status: 'PASS', detail: 'Range: 38-88' },
        { id: 'M2-06', name: 'Final list size', status: 'PASS', detail: '7 items' },
        { id: 'M2-07', name: 'Final from trimmed', status: 'PASS', detail: 'All valid' },
        { id: 'M2-08', name: 'ASINs valid format', status: 'PASS', detail: 'All match pattern' },
      ],
    },
    {
      id: 'M2.1',
      name: 'Customer Intent',
      status: 'REVIEW_NEEDED',
      checksTotal: 7,
      checksPassed: 6,
      checksFailed: 1,
      checks: [
        { id: 'M2.1-01', name: 'Themes count', status: 'PASS', detail: '6 themes' },
        { id: 'M2.1-02', name: 'Unique theme IDs', status: 'PASS', detail: 'All unique' },
        { id: 'M2.1-03', name: 'Theme names valid', status: 'PASS', detail: 'All from vocabulary' },
        { id: 'M2.1-04', name: 'Scores in range', status: 'PASS', detail: 'All 0-100' },
        { id: 'M2.1-05', name: 'Sample quotes exist', status: 'PASS', detail: '3-8 per theme' },
        {
          id: 'M2.1-06',
          name: 'Quotes traceable',
          status: 'REVIEW',
          detail: '1 quote not verified',
          issue: {
            item: 'Theme: RESULTS',
            expected: 'Quote exists in competitor reviews',
            actual: 'Quote not found',
            reason: '"noticed difference in 2 weeks" not found in any review',
          },
          actions: [
            'Verify this quote exists in source data',
            'Replace with verified quote from reviews',
          ],
        },
        { id: 'M2.1-07', name: 'No forbidden topics', status: 'PASS', detail: 'None found' },
      ],
    },
    {
      id: 'M2.3',
      name: 'USP Evaluation',
      status: 'FAIL',
      checksTotal: 7,
      checksPassed: 5,
      checksFailed: 2,
      checks: [
        { id: 'M2.3-01', name: 'Minimum USPs', status: 'PASS', detail: '4 approved' },
        { id: 'M2.3-02', name: 'All have tags', status: 'PASS', detail: '4/4 tagged' },
        {
          id: 'M2.3-03',
          name: 'Proof points valid',
          status: 'FAIL',
          detail: '1 not in Truth Set',
          issue: {
            item: 'USP_02: "Dermatologist recommended"',
            expected: 'Proof point exists in Product Truth Set',
            actual: 'Not found',
            reason: '"recommended by dermatologists" claim has no supporting evidence',
          },
          actions: [
            'Add dermatologist evidence to Truth Set',
            'Rephrase USP without "dermatologist recommended" claim',
          ],
        },
        { id: 'M2.3-04', name: 'Scores correct', status: 'PASS', detail: 'All within ±2' },
        { id: 'M2.3-05', name: 'No banned terms', status: 'PASS', detail: '0 matches' },
        { id: 'M2.3-06', name: 'Priority assigned', status: 'PASS', detail: '4/4 assigned' },
        {
          id: 'M2.3-07',
          name: 'Primary USPs exist',
          status: 'FAIL',
          detail: '1 Primary (need ≥2)',
          issue: {
            item: 'Primary USP count',
            expected: '≥2 Primary USPs',
            actual: '1 Primary USP',
            reason: 'Only USP_01 qualifies as Primary (score ≥70)',
          },
          actions: [
            'Review USP scores and promote a Secondary USP',
            'Add stronger USPs to meet Primary threshold',
          ],
        },
      ],
    },
    {
      id: 'M3',
      name: 'Keyword Intelligence',
      status: 'BLOCKED',
      checksTotal: 8,
      checksPassed: 0,
      checksFailed: 0,
      checks: [
        { id: 'M3-01', name: 'Primary keywords', status: 'BLOCKED' },
        { id: 'M3-02', name: 'All keywords scored', status: 'BLOCKED' },
        { id: 'M3-03', name: 'Score formula correct', status: 'BLOCKED' },
        { id: 'M3-04', name: 'All tiered', status: 'BLOCKED' },
        { id: 'M3-05', name: 'No duplicates', status: 'BLOCKED' },
        { id: 'M3-06', name: 'USP bundles complete', status: 'BLOCKED' },
        { id: 'M3-07', name: 'No risk-high in bundles', status: 'BLOCKED' },
        { id: 'M3-08', name: 'Coverage adequate', status: 'BLOCKED' },
      ],
    },
    {
      id: 'M4',
      name: 'Listing Creation',
      status: 'BLOCKED',
      checksTotal: 10,
      checksPassed: 0,
      checksFailed: 0,
      checks: [
        { id: 'M4-01', name: 'Title length', status: 'BLOCKED' },
        { id: 'M4-02', name: 'Bullet count', status: 'BLOCKED' },
        { id: 'M4-03', name: 'Bullet lengths', status: 'BLOCKED' },
        { id: 'M4-04', name: 'Description length', status: 'BLOCKED' },
        { id: 'M4-05', name: 'Backend size', status: 'BLOCKED' },
        { id: 'M4-06', name: 'No banned terms', status: 'BLOCKED' },
        { id: 'M4-07', name: 'Keyword coverage', status: 'BLOCKED' },
        { id: 'M4-08', name: 'USP coverage', status: 'BLOCKED' },
        { id: 'M4-09', name: 'No ALL CAPS', status: 'BLOCKED' },
        { id: 'M4-10', name: 'Quality score', status: 'BLOCKED' },
      ],
    },
  ],
  summary: {
    totalChecks: 47,
    passed: 26,
    failed: 3,
    review: 1,
    blocked: 17,
  },
};
